import { ApiConfig } from "./api.config"

export const VALID_CONFIG: ApiConfig = {
  url: "base-url",
  timeout: 10000,
}

export const responses = {
  getRecordings: {
    BAD_DATA: { ok: true, data: null },
    PASS: {
      ok: true,
      data: {
        search: {
          org: {
            acronym: "OCEANetwork",
            oid: 104,
            name: "Oregon Christian Home Education Association Network",
          },
        },
        data: [
          {
            LOCATION: "Linn County",
            SET: 1,
            PRICE: 99.0,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-SET",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2602,
            AVAILABLE: 0,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Encouragement", TID: 11 },
              { TOPIC: "Vision", TID: 12 },
              { TOPIC: "Choosing curriculum", TID: 14 },
              { TOPIC: "Preschool", TID: 15 },
              { TOPIC: "Middle school", TID: 17 },
              { TOPIC: "High school", TID: 18 },
              { TOPIC: "Post high school", TID: 19 },
              { TOPIC: "College", TID: 20 },
              { TOPIC: "Practical/How-to", TID: 21 },
              { TOPIC: "Special needs", TID: 24 },
              { TOPIC: "Organization", TID: 25 },
              { TOPIC: "Fathers", TID: 26 },
              { TOPIC: "Mothers", TID: 27 },
              { TOPIC: "Family life/marriage", TID: 30 },
              { TOPIC: "Family discipleship", TID: 31 },
              { TOPIC: "Biblical instruction", TID: 32 },
              { TOPIC: "Children's sessions", TID: 34 },
              { TOPIC: "Young adult sessions", TID: 35 },
              { TOPIC: "Legal/political action", TID: 36 },
              { TOPIC: "World View", TID: 37 },
              { TOPIC: "Entertainment", TID: 38 },
              { TOPIC: "Missions", TID: 39 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION: "",
            SESSIONS: [
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-01",
                FIRSTNAME: "Voddie",
                RID: 2523,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: "Family Worship: The Forgotten Home Discipleship Tool",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-02",
                FIRSTNAME: "David",
                RID: 2569,
                SETID: 2602,
                SID: 795,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Barton",
                TITLE: "American Exceptionalism",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-03",
                FIRSTNAME: "Voddie",
                RID: 2572,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: " Culture Wars: How They Affect the Homeschool Family and How We Respond",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-04",
                FIRSTNAME: "David",
                RID: 2600,
                SETID: 2602,
                SID: 795,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Barton",
                TITLE: "Keeping Truth in History",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-101",
                FIRSTNAME: "Voddie",
                RID: 2525,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: "Bible Study Basics: How to Study and Teach the Bible at Home",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-102",
                FIRSTNAME: "Corey",
                RID: 2603,
                SETID: 2602,
                SID: 777,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Gilbert",
                TITLE: "Sex, Porn, and Your Kids:Age Appropriate Conversations",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-103",
                FIRSTNAME: "Betsy",
                RID: 2527,
                SETID: 2602,
                SID: 91,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Ray",
                TITLE: "Life is a Bowl of Cherries",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-104",
                FIRSTNAME: "Carol",
                RID: 2528,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: "Developing a Plan for High School: Sample Four-Year Plans",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-105",
                FIRSTNAME: "Vicki",
                RID: 2529,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "A Mom's Sentimental Journey",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-106",
                FIRSTNAME: "Eliot",
                RID: 2530,
                SETID: 2602,
                SID: 778,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Grasso",
                TITLE: "Thriving in Higher Education: Opportunities and Challenges",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-107",
                FIRSTNAME: "HELP",
                RID: 2535,
                SETID: 2602,
                SID: 781,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Vendor",
                TITLE: "The Challenged and Challenging Child",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-108",
                FIRSTNAME: "Timothy",
                RID: 2536,
                SETID: 2602,
                SID: 782,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Partners",
                TITLE: "Biblical Stewardship with Continuing Education Credits",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-109",
                FIRSTNAME: "Marianne",
                RID: 2533,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE: "Getting Started Teaching Kids with Learning Difficulties",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-110",
                FIRSTNAME: "Pat",
                RID: 2537,
                SETID: 2602,
                SID: 783,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Roy",
                TITLE: "The Days of Creation",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-152",
                FIRSTNAME: "New",
                RID: 2539,
                SETID: 2602,
                SID: 785,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "StAndrews",
                TITLE: "Why Christian Collegiate Education?",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-153",
                FIRSTNAME: "Institute for ",
                RID: 2540,
                SETID: 2602,
                SID: 369,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Excellence in Writing",
                TITLE: "Experience Excellence in Writing",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-154",
                FIRSTNAME: "",
                RID: 2541,
                SETID: 2602,
                SID: 786,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Little Crews Studio",
                TITLE: "Making the Cut: A Candid Look at Independent Filmmaking",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-155",
                FIRSTNAME: "",
                RID: 2542,
                SETID: 2602,
                SID: 787,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Civil Air Patrol Oregon Wing",
                TITLE: "Emergency Services",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-156",
                FIRSTNAME: "",
                RID: 2543,
                SETID: 2602,
                SID: 788,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "College Prep Genius",
                TITLE: "Top Ten Homeschooling Secrets to Ace the SAT/ACT/PSAT",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-157",
                FIRSTNAME: "Jack",
                RID: 2545,
                SETID: 2602,
                SID: 789,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Dublin",
                TITLE: "Storytellers: The Gatekeepers of our Heritage",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-158",
                FIRSTNAME: "",
                RID: 2548,
                SETID: 2602,
                SID: 791,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Real Life Bible Studies",
                TITLE: "Developing a Quiet Time with God",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-181",
                FIRSTNAME: "Dick",
                RID: 2570,
                SETID: 2602,
                SID: 110,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Karman",
                TITLE: "It's Easy to Homeschool - Dads (and Sons) and Donuts",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-182",
                FIRSTNAME: "Dorothy",
                RID: 2571,
                SETID: 2602,
                SID: 138,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Karman",
                TITLE:
                  "You've Got What It Takes, and It's Not What You Think - Moms (and Daughters) and Muffins",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-201",
                FIRSTNAME: "Voddie",
                RID: 2547,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: "Don't Let Home Education Destroy Your Marriage!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-202",
                FIRSTNAME: "Corey",
                RID: 2549,
                SETID: 2602,
                SID: 777,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Gilbert",
                TITLE: "Leading Your Family in a Tech'ed-Out World-",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-203",
                FIRSTNAME: "Tauna",
                RID: 2550,
                SETID: 2602,
                SID: 792,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Meyer",
                TITLE: "Getting It All Done: Loop Scheduling for Homeschooling and Homemaking",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-204",
                FIRSTNAME: "Carol",
                RID: 2552,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: "High School Transcript Clinic: Practical Help and Tips",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-205",
                FIRSTNAME: "Vicki",
                RID: 2553,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "Exploring Curriculum Options",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-206",
                FIRSTNAME: "",
                RID: 2554,
                SETID: 2602,
                SID: 793,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Living Waters Spanish",
                TITLE: "Evangelism, Mission Trips, and Spanish",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-207",
                FIRSTNAME: "",
                RID: 2555,
                SETID: 2602,
                SID: 794,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Cheryl's Christian Books",
                TITLE: "Key Principles for Living Life with Passion, Purpose, and Victory",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-208",
                FIRSTNAME: "Right Start Mathematics",
                RID: 2556,
                SETID: 2602,
                SID: 765,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "",
                TITLE: "Math is More than Just Numbers with RightStart™ Math",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-209",
                FIRSTNAME: "Marianne",
                RID: 2557,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE: "Avoiding and Overcoming Homeschool Burnout",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-210",
                FIRSTNAME: "Pat",
                RID: 2604,
                SETID: 2602,
                SID: 783,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Roy",
                TITLE: "Made in the Image of God",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-301",
                FIRSTNAME: "David",
                RID: 2559,
                SETID: 2602,
                SID: 795,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Barton",
                TITLE: "God in the Constitution",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-302",
                FIRSTNAME: "Dorothy",
                RID: 2560,
                SETID: 2602,
                SID: 138,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Karman",
                TITLE: "Oregon Homeschool Law: Past, Present and Future",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-302",
                FIRSTNAME: "Rodger",
                RID: 2560,
                SETID: 2602,
                SID: 796,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Williams",
                TITLE: "Oregon Homeschool Law: Past, Present and Future",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-303",
                FIRSTNAME: "Betsy",
                RID: 2561,
                SETID: 2602,
                SID: 91,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Ray",
                TITLE: "#IBELONGTOCHRIST",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-304",
                FIRSTNAME: "Carol",
                RID: 2562,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: "Charting Your Way Through High School for College, Workforce, or Military",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-305",
                FIRSTNAME: "Vicki",
                RID: 2563,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "The Word for Wee Ones",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-306",
                FIRSTNAME: "",
                RID: 2564,
                SETID: 2602,
                SID: 788,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "College Prep Genius",
                TITLE: "Free College at Your Fingertips",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-307",
                FIRSTNAME: "",
                RID: 2565,
                SETID: 2602,
                SID: 787,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Civil Air Patrol Oregon Wing",
                TITLE: "Aerospace Education/STEM",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-308",
                FIRSTNAME: "Sandy",
                RID: 2566,
                SETID: 2602,
                SID: 797,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Belschner",
                TITLE: "Been there. Done That. Still Doing It!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-309",
                FIRSTNAME: "Marianne",
                RID: 2567,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE:
                  "Help for the Hopelessly Unorganized Child: ?Homeschooling Kids with ADD or ADHD",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-310",
                FIRSTNAME: "Pat",
                RID: 2568,
                SETID: 2602,
                SID: 783,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Roy",
                TITLE: "Dinosaurs and the Bible",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-401",
                FIRSTNAME: "David",
                RID: 2573,
                SETID: 2602,
                SID: 795,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Barton",
                TITLE: "Four Centuries of American Education",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-402",
                FIRSTNAME: "Voddie",
                RID: 2574,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: "The Christian Man as Father",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-404",
                FIRSTNAME: "Carol",
                RID: 2575,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: "Essential Skills for Successful Teens: Study and Time Management",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-405",
                FIRSTNAME: "Vicki",
                RID: 2576,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "Hope for the Organizationally Challenged",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-406",
                FIRSTNAME: "Jean",
                RID: 2577,
                SETID: 2602,
                SID: 411,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Burk",
                TITLE: "Build an Amazing Homeschool Transcript",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-406",
                FIRSTNAME: "",
                RID: 2577,
                SETID: 2602,
                SID: 788,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "College Prep Genius",
                TITLE: "Build an Amazing Homeschool Transcript",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-409",
                FIRSTNAME: "Marianne",
                RID: 2578,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE: "Fearfully and Wonderfully Made",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-452",
                FIRSTNAME: "",
                RID: 2579,
                SETID: 2602,
                SID: 799,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Mission Aviation Fellowship",
                TITLE: "What It Takes to Be a Missionary Pilot!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-453",
                FIRSTNAME: "HELP",
                RID: 2580,
                SETID: 2602,
                SID: 781,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Vendor",
                TITLE: "The Challenged and Challenging Child",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-454",
                FIRSTNAME: "",
                RID: 2581,
                SETID: 2602,
                SID: 787,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Civil Air Patrol Oregon Wing",
                TITLE: "Hands-on Aerospace Activities",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-455",
                FIRSTNAME: "Classical Conversations",
                RID: 2582,
                SETID: 2602,
                SID: 768,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "",
                TITLE: "The Art of Grammar Across the Ages",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-456",
                FIRSTNAME: "Accelerated Christian Education",
                RID: 2583,
                SETID: 2602,
                SID: 639,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "",
                TITLE: "Making a Difference: Children with Character",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-457",
                FIRSTNAME: "Jack",
                RID: 2605,
                SETID: 2602,
                SID: 789,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Dublin",
                TITLE: "Written In The Stars:",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-458",
                FIRSTNAME: "Right Start Mathematics",
                RID: 2585,
                SETID: 2602,
                SID: 765,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "",
                TITLE: "Fractions: From Fear to Fun with RightStart™ Math!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-501",
                FIRSTNAME: "David",
                RID: 2586,
                SETID: 2602,
                SID: 795,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Barton",
                TITLE: "Know the Bible",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-502",
                FIRSTNAME: "",
                RID: 2587,
                SETID: 2602,
                SID: 800,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "OCEAN Freedom Watch Team",
                TITLE:
                  "Our Valuable Homeschool Freedoms: Remain Vigilant, Be Vocal, Experience Victory",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-503",
                FIRSTNAME: "Corey",
                RID: 2588,
                SETID: 2602,
                SID: 777,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Gilbert",
                TITLE: "Developing and Teaching Your Family a Biblical Sexual Ethic",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-504",
                FIRSTNAME: "Carol",
                RID: 2589,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: "The College Admissions Process: The Homeschooled Student's Guide",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-505",
                FIRSTNAME: "Vicki",
                RID: 2590,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "Homeschooling Middles While You Still Have Littles",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-506",
                FIRSTNAME: "",
                RID: 2591,
                SETID: 2602,
                SID: 788,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "College Prep Genius",
                TITLE: "Best Kept Secret to Free College: The PSAT",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-509",
                FIRSTNAME: "Marianne",
                RID: 2592,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE:
                  "You Can Homeschool Your Child with Dyscalculia, Dysgraphia, and Dyslexia: Identifying, Accommodating, and Remediating",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-601",
                FIRSTNAME: "Voddie",
                RID: 2593,
                SETID: 2602,
                SID: 239,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Baucham",
                TITLE: "Biblical Manhood in the Home",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-602",
                FIRSTNAME: "Dr. Brian",
                RID: 2594,
                SETID: 2602,
                SID: 90,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Ray",
                TITLE: "Homeschool Child Abuse, Government Control, and Homeschool Freedoms",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-603",
                FIRSTNAME: "Joyce",
                RID: 2595,
                SETID: 2602,
                SID: 366,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Padilla",
                TITLE: "This is My Story. This is My Song!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-604",
                FIRSTNAME: "Carol",
                RID: 2596,
                SETID: 2602,
                SID: 681,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Becker",
                TITLE: " You Can Homeschool High School…If You Can Make It Through Tomorrow!",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-605",
                FIRSTNAME: "Vicki",
                RID: 2597,
                SETID: 2602,
                SID: 27,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Bentley",
                TITLE: "When Life Broadsides Your Homeschool",
                SETTITLE: "2018 Complete Conference Set",
              },
              {
                PRICE: 99.0,
                REGULARPRICE: 310.5,
                RECID: "18-SET",
                RECORDINGID: "18-609",
                FIRSTNAME: "Marianne",
                RID: 2599,
                SETID: 2602,
                SID: 798,
                VARSETID: 2602,
                DESCRIPTION: "",
                LASTNAME: "Sunderland",
                TITLE: "Raising Kids with Vision",
                SETTITLE: "2018 Complete Conference Set",
              },
            ],
            TITLE: "2018 Complete Conference Set",
            SPEAKERS: [
              { LASTNAME: "Bentley", FIRSTNAME: "Vicki", SID: 27 },
              { LASTNAME: "Ray", FIRSTNAME: "Dr. Brian", SID: 90 },
              { LASTNAME: "Ray", FIRSTNAME: "Betsy", SID: 91 },
              { LASTNAME: "Karman", FIRSTNAME: "Dick", SID: 110 },
              { LASTNAME: "Karman", FIRSTNAME: "Dorothy", SID: 138 },
              { LASTNAME: "Baucham", FIRSTNAME: "Voddie", SID: 239 },
              { LASTNAME: "Padilla", FIRSTNAME: "Joyce", SID: 366 },
              {
                LASTNAME: "Excellence in Writing",
                FIRSTNAME: "Institute for ",
                SID: 369,
              },
              { LASTNAME: "Burk", FIRSTNAME: "Jean", SID: 411 },
              {
                LASTNAME: "",
                FIRSTNAME: "Accelerated Christian Education",
                SID: 639,
              },
              { LASTNAME: "Becker", FIRSTNAME: "Carol", SID: 681 },
              { LASTNAME: "", FIRSTNAME: "Right Start Mathematics", SID: 765 },
              { LASTNAME: "", FIRSTNAME: "Classical Conversations", SID: 768 },
              { LASTNAME: "Gilbert", FIRSTNAME: "Corey", SID: 777 },
              { LASTNAME: "Grasso", FIRSTNAME: "Eliot", SID: 778 },
              { LASTNAME: "Vendor", FIRSTNAME: "HELP", SID: 781 },
              { LASTNAME: "Partners", FIRSTNAME: "Timothy", SID: 782 },
              { LASTNAME: "Roy", FIRSTNAME: "Pat", SID: 783 },
              { LASTNAME: "StAndrews", FIRSTNAME: "New", SID: 785 },
              { LASTNAME: "Little Crews Studio", FIRSTNAME: "", SID: 786 },
              {
                LASTNAME: "Civil Air Patrol Oregon Wing",
                FIRSTNAME: "",
                SID: 787,
              },
              { LASTNAME: "College Prep Genius", FIRSTNAME: "", SID: 788 },
              { LASTNAME: "Dublin", FIRSTNAME: "Jack", SID: 789 },
              { LASTNAME: "Real Life Bible Studies", FIRSTNAME: "", SID: 791 },
              { LASTNAME: "Meyer", FIRSTNAME: "Tauna", SID: 792 },
              { LASTNAME: "Living Waters Spanish", FIRSTNAME: "", SID: 793 },
              { LASTNAME: "Cheryl's Christian Books", FIRSTNAME: "", SID: 794 },
              { LASTNAME: "Barton", FIRSTNAME: "David", SID: 795 },
              { LASTNAME: "Williams", FIRSTNAME: "Rodger", SID: 796 },
              { LASTNAME: "Belschner", FIRSTNAME: "Sandy", SID: 797 },
              { LASTNAME: "Sunderland", FIRSTNAME: "Marianne", SID: 798 },
              {
                LASTNAME: "Mission Aviation Fellowship",
                FIRSTNAME: "",
                SID: 799,
              },
              { LASTNAME: "OCEAN Freedom Watch Team", FIRSTNAME: "", SID: 800 },
            ],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-01",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2523,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Encouragement", TID: 11 },
              { TOPIC: "Family life/marriage", TID: 30 },
              { TOPIC: "Biblical instruction", TID: 32 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "\r\nTwo hundred years ago a man could be excommunicated from his church for failing to lead his household in regular family worship. Today a man can become a pastor without ever having engaged in the process. Learn the history, theology, and importance of family worship, along with gaining practical tips any family can follow to institute this vital practice. \r\n",
            SESSIONS: "",
            TITLE: "Family Worship: The Forgotten Home Discipleship Tool",
            SPEAKERS: [{ LASTNAME: "Baucham", FIRSTNAME: "Voddie", SID: 239 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-02",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2569,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Encouragement", TID: 11 },
              { TOPIC: "Vision", TID: 12 },
              { TOPIC: "Legal/political action", TID: 36 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "America’s exceptionalism encompasses great diversity of race, ethnicity, and religion, and has benefited every American. For several decades of indoctrination in both education and politics, we have been taught America's flaws but little of its matchless benefits. Five principles set forth in the Declaration of Independence have produced blessings for America. Discover these principles and learn what every citizen can do to restore America.",
            SESSIONS: "",
            TITLE: "American Exceptionalism",
            SPEAKERS: [{ LASTNAME: "Barton", FIRSTNAME: "David", SID: 795 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-03",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2572,
            AVAILABLE: 1,
            DATE: "June, 23 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Encouragement", TID: 11 },
              { TOPIC: "Vision", TID: 12 },
              { TOPIC: "World View", TID: 37 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              'There is a mighty clash of worldviews going on all around us, and there is no way to escape. Educating our children at home will only postpone the inevitable. Will our children engage their culture as lambs going to slaughter, or as sheep among wolves, being "wise as serpents and innocent as doves" (Matthew 10:16)? ',
            SESSIONS: "",
            TITLE: " Culture Wars: How They Affect the Homeschool Family and How We Respond",
            SPEAKERS: [{ LASTNAME: "Baucham", FIRSTNAME: "Voddie", SID: 239 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-04",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2600,
            AVAILABLE: 1,
            DATE: "June, 23 2018 00:00:00",
            TOPICS: [{ TOPIC: "Vision", TID: 12 }, { TOPIC: "World View", TID: 37 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "America has developed a severe case of historical amnesia. Not only have we forgotten how we became the most stable and prosperous nation on the globe, but now we often feel compelled to apologize to the world just for being Americans. Five specific historical attacks launched over the past century have now found a permanent home in American media and education. Learn about the five attacks and how to quickly identify and negate their harmful influence. Preserve the understanding of America’s greatness for generations to come.",
            SESSIONS: "",
            TITLE: "Keeping Truth in History",
            SPEAKERS: [{ LASTNAME: "Barton", FIRSTNAME: "David", SID: 795 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-101",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2525,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Family discipleship", TID: 31 },
              { TOPIC: "Biblical instruction", TID: 32 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "What good is home education if the Bible is not central to all we do? However, often parents feel inadequate to interpret Scripture and teach it to their children. Revive your own study of Scripture and spark your family devotions by implementing Dr. Baucham's practical suggestions.",
            SESSIONS: "",
            TITLE: "Bible Study Basics: How to Study and Teach the Bible at Home",
            SPEAKERS: [{ LASTNAME: "Baucham", FIRSTNAME: "Voddie", SID: 239 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-102",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2603,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Family life/marriage", TID: 30 },
              { TOPIC: "Biblical instruction", TID: 32 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "This session will help parents move past the awkwardness inherent in topics regarding sexuality and provide you with ideas and resources to incorporate into your family conversations.",
            SESSIONS: "",
            TITLE: "Sex, Porn, and Your Kids:Age Appropriate Conversations",
            SPEAKERS: [{ LASTNAME: "Gilbert", FIRSTNAME: "Corey", SID: 777 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-103",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2527,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Encouragement", TID: 11 },
              { TOPIC: "Mothers", TID: 27 },
              { TOPIC: "Biblical instruction", TID: 32 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Life can be sweet, refreshing, and joyful. Do your children and spouse see God’s joy in you? Do they get refreshed by your joyful spirit? God gives us joy (Ecc. 2:26), He is our joy (Ps. 43:4), and He commands us to be joyful (Phil. 4:4) and full of joy (Jn. 15:11) regardless of our circumstances (Heb. 10:34). No matter your personality type, God wants you to bear His Spirit to your family. Come ready to be rejuvenated and encouraged to “rejoice in all to which you have put your hand, you and your household” (Deut. 12:7).",
            SESSIONS: "",
            TITLE: "Life is a Bowl of Cherries",
            SPEAKERS: [{ LASTNAME: "Ray", FIRSTNAME: "Betsy", SID: 91 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-104",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2528,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "High school", TID: 18 }, { TOPIC: "Practical/How-to", TID: 21 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Carol will guide parents in considering critical aspects of a high school student’s homeschool plan. Topics presented will include what subjects to teach and their timing, whether to follow a basic high school plan or a rigorous college prep plan, how to evaluate credits and determine grades, and whether or not transcripts and diplomas are needed. If you are beginning to think about homeschooling during the high school years, this seminar will help you organize your thoughts so you can begin laying the groundwork for a viable four-year plan.\r\n\r\nHandouts: http://www.oceanetwork.org/wp-content/uploads/Developing-High-School-Plan.pdf\r\n",
            SESSIONS: "",
            TITLE: "Developing a Plan for High School: Sample Four-Year Plans",
            SPEAKERS: [{ LASTNAME: "Becker", FIRSTNAME: "Carol", SID: 681 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-105",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2529,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Encouragement", TID: 11 }, { TOPIC: "Practical/How-to", TID: 21 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Twenty-plus years and seventeen kids later, what a veteran homeschool mom would repeat and what she would do differently on this homeschooling journey!",
            SESSIONS: "",
            TITLE: "A Mom's Sentimental Journey",
            SPEAKERS: [{ LASTNAME: "Bentley", FIRSTNAME: "Vicki", SID: 27 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-106",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2530,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Post high school", TID: 19 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "In this workshop, Dr. Eliot Grasso examines the preconceptions, opportunities, and challenges for Christian homeschoolers who are exploring and participating in higher education. The objective of this workshop is to give insider perspectives on Christian and secular institutions so that families can make informed decisions about the next critical developmental step in their children's education.",
            SESSIONS: "",
            TITLE: "Thriving in Higher Education: Opportunities and Challenges",
            SPEAKERS: [{ LASTNAME: "Grasso", FIRSTNAME: "Eliot", SID: 778 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-107",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2535,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Practical/How-to", TID: 21 }, { TOPIC: "Special needs", TID: 24 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Help for the parents who have tried everything and are at their wits end. HELP has been working with families to HELP Elevate Learning Processing for over 30 years.",
            SESSIONS: "",
            TITLE: "The Challenged and Challenging Child",
            SPEAKERS: [{ LASTNAME: "Vendor", FIRSTNAME: "HELP", SID: 781 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-108",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2536,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Practical/How-to", TID: 21 },
              { TOPIC: "Biblical instruction", TID: 32 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Learn what the Bible has to say about financial stewardship, which includes debt, budgeting, investing and a lesser known concept—stewardship of culture. Discover how your homeschooler can earn continuing education credits through the process.",
            SESSIONS: "",
            TITLE: "Biblical Stewardship with Continuing Education Credits",
            SPEAKERS: [{ LASTNAME: "Partners", FIRSTNAME: "Timothy", SID: 782 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-109",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2533,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Special needs", TID: 24 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "With wisdom and understanding, Marianne offers encouragement in making the decision to homeschool. She will equip you to answer critics who insist schools are the educational experts, tell you how to overcome common emotional issues for parents and kids, share the legalities of home education, and give you tips for finding local support. ?Marianne will share the truth about the state of special education in public schools, tips on finding and identifying homeschool curriculum for the dyslexic student, and strategies for getting it all done. She will also discuss teaching methods, when to get help in the form of diagnostic testing and educational therapy, and how to balance accommodations and remediations. *Complimentary coffee served during Marianne’s sessions.",
            SESSIONS: "",
            TITLE: "Getting Started Teaching Kids with Learning Difficulties",
            SPEAKERS: [{ LASTNAME: "Sunderland", FIRSTNAME: "Marianne", SID: 798 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-110",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2537,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Children's sessions", TID: 34 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Join Pat and travel through the first six days of earth history as you learn about scientific and biblical creation.",
            SESSIONS: "",
            TITLE: "The Days of Creation",
            SPEAKERS: [{ LASTNAME: "Roy", FIRSTNAME: "Pat", SID: 783 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-152",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2539,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Post high school", TID: 19 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "As the culture disintegrates around us, why not encourage your students to pursue an education that will equip them for Christian leadership through the power of the Gospel? This education will not be just a train ticket to the next job, but a prized foundation for their lifetime of cultural leadership through Christian fearlessness wherever God calls them to serve.",
            SESSIONS: "",
            TITLE: "Why Christian Collegiate Education?",
            SPEAKERS: [{ LASTNAME: "StAndrews", FIRSTNAME: "New", SID: 785 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-153",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2540,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Practical/How-to", TID: 21 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Discover award-winning Excellence in Writing, a method of teaching composition that really works. Using this program, students of all ages will learn to write stories, reports, and essays with style. This workshop will give you an overview of the program and show you how to get started.",
            SESSIONS: "",
            TITLE: "Experience Excellence in Writing",
            SPEAKERS: [
              {
                LASTNAME: "Excellence in Writing",
                FIRSTNAME: "Institute for ",
                SID: 369,
              },
            ],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-154",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2541,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Practical/How-to", TID: 21 }, { TOPIC: "Entertainment", TID: 38 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "This is a crash course for those interested in filmmaking. Joel Steege, director/producer of The Runner from Ravenshead and The Defense of New Haven, shares just what it takes to make an independent Christian film. Bonus: view newly-released behind-the-scenes footage from Little Crew Studios' productions.",
            SESSIONS: "",
            TITLE: "Making the Cut: A Candid Look at Independent Filmmaking",
            SPEAKERS: [{ LASTNAME: "Little Crews Studio", FIRSTNAME: "", SID: 786 }],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-155",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2542,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [{ TOPIC: "Practical/How-to", TID: 21 }],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Be part of the solution during a natural disaster. Learn to be prepared and how to act in your local community.",
            SESSIONS: "",
            TITLE: "Emergency Services",
            SPEAKERS: [
              {
                LASTNAME: "Civil Air Patrol Oregon Wing",
                FIRSTNAME: "",
                SID: 787,
              },
            ],
            CID: 67,
          },
          {
            LOCATION: "Linn County",
            SET: 0,
            PRICE: 4.5,
            ORG: "Oregon Christian Home Education Association Network",
            RECID: "18-156",
            CONFSTART: "June, 22 2018 00:00:00",
            CONFEND: "June, 23 2018 00:00:00",
            OID: 104,
            RID: 2543,
            AVAILABLE: 1,
            DATE: "June, 22 2018 00:00:00",
            TOPICS: [
              { TOPIC: "Post high school", TID: 19 },
              { TOPIC: "College", TID: 20 },
              { TOPIC: "Practical/How-to", TID: 21 },
            ],
            CONFERENCE: "OR-2018 Build Your House - Homeschooling for the Kingdom",
            DESCRIPTION:
              "Homeschoolers are not at a disadvantage when it comes to acing standardized tests. But there are little-known secrets that can hinder scores and scholarship money. We uncover wrong information that has been perpetrated for years. Discover why colleges are coveting homeschoolers and how they use tests like the SAT/ACT and PSAT to validate the transcript. You will join tens of thousands of informed families and walk away knowing the key to beating these tests and how your student can receive life-changing, incredible scholarship money.",
            SESSIONS: "",
            TITLE: "Top Ten Homeschooling Secrets to Ace the SAT/ACT/PSAT",
            SPEAKERS: [{ LASTNAME: "College Prep Genius", FIRSTNAME: "", SID: 788 }],
            CID: 67,
          },
        ],
        totalRecords: 751,
      },
    },
  },
}
